# this is a comment
stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  build_features:
    cmd: python src/features/build_features.py
    deps:
    - data/interim
    - src/features/build_features.py
    outs:
    - data/features
  train_model:
    cmd: python src/models/train_model.py
    deps:
    - data/features
    - src/models/train_model.py
    outs:
    - models/model.pkl
  predict_model:
    cmd: python src/models/predict_model.py
    deps:
    - models/model.pkl
    - src/models/predict_model.py
    outs:
    - reports/metrics.json
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/interim
